require("user.options")
require("user.keymaps")
require("user.plugins")

-- require("user.filetype")
-- require("user.ftdetect.astro")
require("user.autocommands")

-- require("user.colorscheme")
require("user.onedark")
-- require("user.material")

require("user.cmp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.illuminate")
require("user.indentline")
require("user.alpha")

require("user.lsp")
-- require("user.lspconfig")

require("user.dap")
require("user.whichkey")
require("user.ufo")
